<?php

/**
 * @file
 */

/**
 * Dumps theme hook suggestions for preprocessed items.
 *
 * @param $variables
 * @param string $hook
 */
function _template_suggestion_finder_suggestions_dump($variables, $hook = 'None Provided') {
  if (!empty($variables['theme_hook_suggestions'])) {
    $active_suggestions = $variables['theme_hook_suggestions'];
    $active_suggestions = array_reverse($active_suggestions);
    $active_suggestions = implode(' > ', $active_suggestions);
    $active_suggestions = str_replace('_', '-', $active_suggestions);
    dsm($active_suggestions);
  }
}

/**
 * Implements hook_preprocess().
 */
function template_suggestion_finder_preprocess(&$variables, $hook) {
  _template_suggestion_finder_suggestions_dump($variables, $hook);
}

/**
 * Implements hook_preprocess_field().
 */
function template_suggestion_finder_preprocess_field(&$variables) {
  _template_suggestion_finder_suggestions_dump($variables, 'field');
}

/**
 * Implements hook_page_build().
 */
function template_suggestion_finder_page_build(&$page) {
  dsm('Template suggestions enabled. Please note that this will not ' .
    'display views suggestions');
}
